spring:
  application:
    name: myblog-site

  # settings for h2 database
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql

  # datasource configurations
  datasource:
    url: jdbc:h2:mem:myblog;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: root
    password: root
    driver-class-name: org.h2.Driver

  # multipart configurations
  servlet:
    multipart:
      enabled: true # Enable multipart file uploads (enabled by default)
      max-file-size: 10MB # Maximum size for an uploaded file
      max-request-size: 10MB # Maximum size for a multipart request (e.g. total upload size)

# logging
logging:
  level:
    org.javaprojects: INFO


# specifies a URI for uploading that is inside the project.
# it must end with a name of the directory that specified in 'application.images.image-directory' property
# Ex: if application.images.image-directory=/upload
#     then:  application.images.upload-directory=file:/home/user/myblog/src/main/webapp/upload
# you can use only 'file:' or 'classpath:' schemes of location.
application:
  images:
    upload-directory-location-path: classpath:/static/upload
    upload-directory-handler-path: /upload
    default-image-path: /images/default_image.jpg


